# Amazon Review Dataset

## Week 1 - Data Preprocessing

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../dataset/amazon_review.csv")

In [3]:
df.head()

,reviewerID,asin,reviewerName,helpful,reviewText,overall,summary,unixReviewTime,reviewTime,day_diff,helpful_yes,total_vote
0,A3SBTW3WS4IQSN,B007WTAJTO,NaN,"[0, 0]",No issues.,4.0,Four Stars,1406073600,2014-07-23,138,0,0
1,A18K1ODH1I2MVB,B007WTAJTO,0mie,"[0, 0]","Purchased this for my device, it worked as adv...",5.0,MOAR SPACE!!!,1382659200,2013-10-25,409,0,0
2,A2FII3I2MBMUIA,B007WTAJTO,1K3,"[0, 0]",it works as expected. I should have sprung for...,4.0,nothing to really say....,1356220800,2012-12-23,715,0,0
3,A3H99DFEG68SR,B007WTAJTO,1m2,"[0, 0]",This think has worked out great.Had a diff. br...,5.0,Great buy at this price!!! *** UPDATE,1384992000,2013-11-21,382,0,0
4,A375ZM4U047O79,B007WTAJTO,2&amp;1/2Men,"[0, 0]","Bought it with Retail Packaging, arrived legit...",5.0,best deal around,1373673600,2013-07-13,513,0,0

In [4]:
df.shape

(4915, 12)

In [5]:
df.columns

Index(['reviewerID', 'asin', 'reviewerName', 'helpful', 'reviewText',
       'overall', 'summary', 'unixReviewTime', 'reviewTime', 'day_diff',
       'helpful_yes', 'total_vote'],
      dtype='str')

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4915 entries, 0 to 4914
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   reviewerID      4915 non-null   str
 1   asin            4915 non-null   str
 2   reviewerName    4914 non-null   str
 3   helpful         4915 non-null   str
 4   reviewText      4914 non-null   str
 5   overall         4915 non-null   float64
 6   summary         4915 non-null   str
 7   unixReviewTime  4915 non-null   int64
 8   reviewTime      4915 non-null   str
 9   day_diff        4915 non-null   int64
 10  helpful_yes     4915 non-null   int64
 11  total_vote      4915 non-null   int64
dtypes: float64(1), int64(4), str(7)
memory usage: 460.9 KB

In [7]:
df.describe()

           overall  unixReviewTime     day_diff  helpful_yes   total_vote
count  4915.000000    4.915000e+03  4915.000000  4915.000000  4915.000000
mean      4.587589    1.379465e+09   437.367040     1.311089     1.521465
std       0.996845    1.581857e+07   209.439871    41.619161    44.123095
min       1.000000    1.339200e+09     1.000000     0.000000     0.000000
25%       5.000000    1.365898e+09   281.000000     0.000000     0.000000
50%       5.000000    1.381277e+09   431.000000     0.000000     0.000000
75%       5.000000    1.392163e+09   601.000000     0.000000     0.000000
max       5.000000    1.406074e+09  1064.000000  1952.000000  2020.000000

In [8]:
df.isnull().sum()

reviewerID        0
asin              0
reviewerName      1
helpful           0
reviewText        1
overall           0
summary           0
unixReviewTime    0
reviewTime        0
day_diff          0
helpful_yes       0
total_vote        0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df = df.drop_duplicates()

In [11]:
df = df.dropna()

In [12]:
text_columns = ["reviewText", "summary"]

for column in text_columns:
    df[column] = df[column].str.lower().str.strip()

In [13]:
df["reviewTime"] = pd.to_datetime(df["reviewTime"])

In [14]:
df.info()

<class 'pandas.DataFrame'>
Index: 4913 entries, 1 to 4914
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   reviewerID      4913 non-null   str
 1   asin            4913 non-null   str
 2   reviewerName    4913 non-null   str
 3   helpful         4913 non-null   str
 4   reviewText      4913 non-null   str
 5   overall         4913 non-null   float64
 6   summary         4913 non-null   str
 7   unixReviewTime  4913 non-null   int64
 8   reviewTime      4913 non-null   datetime64[us]
 9   day_diff        4913 non-null   int64
 10  helpful_yes     4913 non-null   int64
 11  total_vote      4913 non-null   int64
dtypes: datetime64[us](1), float64(1), int64(4), str(6)
memory usage: 499.0 KB

In [15]:
df.to_csv("../dataset/cleaned_amazon_review.csv", index=False)

In [16]:
df.head()

,reviewerID,asin,reviewerName,helpful,reviewText,overall,summary,unixReviewTime,reviewTime,day_diff,helpful_yes,total_vote
1,A18K1ODH1I2MVB,B007WTAJTO,0mie,"[0, 0]","purchased this for my device, it worked as adv...",5.0,moar space!!!,1382659200,2013-10-25,409,0,0
2,A2FII3I2MBMUIA,B007WTAJTO,1K3,"[0, 0]",it works as expected. i should have sprung for...,4.0,nothing to really say....,1356220800,2012-12-23,715,0,0
3,A3H99DFEG68SR,B007WTAJTO,1m2,"[0, 0]",this think has worked out great.had a diff. br...,5.0,great buy at this price!!! *** update,1384992000,2013-11-21,382,0,0
4,A375ZM4U047O79,B007WTAJTO,2&amp;1/2Men,"[0, 0]","bought it with retail packaging, arrived legit...",5.0,best deal around,1373673600,2013-07-13,513,0,0
5,A2IDCSC6NVONIZ,B007WTAJTO,2Cents!,"[0, 0]",it's mini storage. it doesn't do anything els...,5.0,not a lot to really be said,1367193600,2013-04-29,588,0,0

In [17]:
print("Week 1 preprocessing completed successfully.")

Week 1 preprocessing completed successfully.