# Spam Email Dataset

## Week 3 - Data Preprocessing

In [20]:
import pandas as pd
import numpy as np

In [21]:
df = pd.read_csv("../dataset/email_dataset.csv")

In [22]:
df.head()

,from,to,subject,date,body,label
0,Robert Elz <kre@munnari.OZ.AU>,Chris Garrigues <cwg-dated-1030377287.06fa6d@D...,Re: New Sequences Window,"Thu, 22 Aug 2002 18:26:25 +0700","Date: Wed, 21 Aug 2002 10:54:46 -05...",0
1,Steve Burt <Steve_Burt@cursor-system.com>,"""'zzzzteana@yahoogroups.com'"" <zzzzteana@yahoo...",[zzzzteana] RE: Alexander,"Thu, 22 Aug 2002 12:46:18 +0100","Martin A posted:\nTassos Papadopoulos, the Gre...",0
2,Tim Chapman <timc@2ubh.com>,zzzzteana <zzzzteana@yahoogroups.com>,[zzzzteana] Moscow bomber,"Thu, 22 Aug 2002 13:52:38 +0100",Man Threatens Explosion In Moscow \n\nThursday...,0
3,Monty Solomon <monty@roscom.com>,undisclosed-recipient:;,[IRR] Klez: The Virus That Won't Die,"Thu, 22 Aug 2002 09:15:25 -0400",Klez: The Virus That Won't Die\n \nAlready the...,0
4,Stewart Smith <Stewart.Smith@ee.ed.ac.uk>,zzzzteana@yahoogroups.com,Re: [zzzzteana] Nothing like mama used to make,"Thu, 22 Aug 2002 14:38:22 +0100","> in adding cream to spaghetti carbonara, whi...",0

In [23]:
df.shape

(3000, 6)

In [24]:
df.columns

Index(['from', 'to', 'subject', 'date', 'body', 'label'], dtype='str')

In [25]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   from     3000 non-null   str
 1   to       2844 non-null   str
 2   subject  2998 non-null   str
 3   date     3000 non-null   str
 4   body     2972 non-null   str
 5   label    3000 non-null   int64
dtypes: int64(1), str(5)
memory usage: 140.8 KB

In [26]:
df.describe()

             label
count  3000.000000
mean      0.166667
std       0.372740
min       0.000000
25%       0.000000
50%       0.000000
75%       0.000000
max       1.000000

In [27]:
df.isnull().sum()

from         0
to         156
subject      2
date         0
body        28
label        0
dtype: int64

In [28]:
df.duplicated().sum()

np.int64(6)

In [29]:
df = df.drop_duplicates()

In [30]:
text_columns = ["from", "to", "subject", "body"]

for column in text_columns:
    df[column] = df[column].fillna("")

In [31]:
text_columns = ["from", "to", "subject", "body"]

for column in text_columns:
    df[column] = df[column].str.strip().str.lower()

In [32]:
df["body"] = df["body"].fillna("")
df = df[df["body"].str.strip() != ""]

In [33]:
df["body"].isnull().sum()
(df["body"].str.strip() == "").sum()

np.int64(0)

In [34]:
df["date"] = pd.to_datetime(df["date"], errors="coerce", utc=True)

In [35]:
df["label"].unique()
df["label"].value_counts()

label
0    2498
1     468
Name: count, dtype: int64

In [36]:
df.info()

<class 'pandas.DataFrame'>
Index: 2966 entries, 0 to 2999
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   from     2966 non-null   str
 1   to       2966 non-null   str
 2   subject  2966 non-null   str
 3   date     2964 non-null   datetime64[us, UTC]
 4   body     2966 non-null   str
 5   label    2966 non-null   int64
dtypes: datetime64[us, UTC](1), int64(1), str(4)
memory usage: 162.2 KB

In [37]:
df.head()

,from,to,subject,date,body,label
0,robert elz <kre@munnari.oz.au>,chris garrigues <cwg-dated-1030377287.06fa6d@d...,re: new sequences window,2002-08-22 11:26:25+00:00,"date: wed, 21 aug 2002 10:54:46 -0500\n...",0
1,steve burt <steve_burt@cursor-system.com>,"""'zzzzteana@yahoogroups.com'"" <zzzzteana@yahoo...",[zzzzteana] re: alexander,2002-08-22 11:46:18+00:00,"martin a posted:\ntassos papadopoulos, the gre...",0
2,tim chapman <timc@2ubh.com>,zzzzteana <zzzzteana@yahoogroups.com>,[zzzzteana] moscow bomber,2002-08-22 12:52:38+00:00,man threatens explosion in moscow \n\nthursday...,0
3,monty solomon <monty@roscom.com>,undisclosed-recipient:;,[irr] klez: the virus that won't die,2002-08-22 13:15:25+00:00,klez: the virus that won't die\n \nalready the...,0
4,stewart smith <stewart.smith@ee.ed.ac.uk>,zzzzteana@yahoogroups.com,re: [zzzzteana] nothing like mama used to make,2002-08-22 13:38:22+00:00,"> in adding cream to spaghetti carbonara, whi...",0

In [38]:
df.to_csv("../dataset/cleaned_spam_email.csv", index=False)

In [39]:
print("Week 3 preprocessing completed successfully.")

Week 3 preprocessing completed successfully.